### ISSUE TITLE
Java level error when running swagger gen command

### ISSUE THREAD

**Issue by SupunS** [ballerina-lang/tool-swagger-ballerina#76]
This is to track https://github.com/ballerinalang/ballerina/issues/2760.

**Context:**

Command :

ballerina swagger connector http://petstore.swagger.io/v2/swagger.json -d server/petstore/ -p wso2.carbon.test
or
ballerina swagger skeleton [-d ] [-p ]
Error:
ballerina: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V

**Comment by lankavitharana** [comment]
Closing this as this repository is no longer used, original issue reopened ballerinalang/ballerina#2760.
